
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Stack with selectable VPC and subnet

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: Select an allowed EC2 instance type

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Choose a subnet

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: MyEC2Instance
