
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Stack with three subnets

Resources:
  VPCLookup:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPCLookup

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCLookup
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Subnet1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCLookup
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Subnet2

  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCLookup
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Subnet3

Outputs:
  VPCId:
    Value: !Ref VPCLookup
  Subnet1Id:
    Value: !Ref Subnet1
  Subnet2Id:
    Value: !Ref Subnet2
  Subnet3Id:
    Value: !Ref Subnet3
