AWSTemplateFormatVersion: '2010-09-09'
Description: Modular EC2 stack that consumes VPC and Subnet IDs
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID from the VPC module
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet ID from the VPC module
  InstanceType:
    Type: String
    Description: Select an allowed EC2 instance type
    AllowedValues:
    - t2.micro
    - t3.micro
    Default: t2.micro
    ConstraintDescription: Must be t2.micro or t3.micro
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Fn::Sub: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      SubnetId:
        Ref: SubnetId
      Tags:
      - Key: Name
        Value: ModularEC2Instance
      - Key: Environment
        Value: Dev
Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value:
      Ref: EC2Instance
