AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a sample EC2 instance with restricted instance types and dynamicAMI resolution (no SSH access)
Parameters:
  InstanceType:
    Type: String
    Description: Select an allowed EC2 instance type
    AllowedValues:
    - t2.micro
    - t3.micro
    Default: t2.micro
    ConstraintDescription: Must be t2.micro or t3.micro
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Fn::Sub: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      Tags:
      - Key: Name
        Value: SSMReadyEC2Instance
      - Key: Environment
        Value: Dev
Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value:
      Ref: EC2Instance
