
AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack

Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
    Description: Select one of the allowed instance types
  VPCTemplateURL:
    Type: String
  RDSTemplateURL:
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VPCTemplateURL

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Ref RDSTemplateURL
      Parameters:
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBInstanceClass: !Ref DBInstanceClass
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
